<a href="https://colab.research.google.com/github/Natasha1305/LEARN.PY/blob/main/TASK-10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [9]:
#please provide your answer below this line.
import numpy as np
matrix1 = np.random.randn(3,3)
matrix2 = np.random.randn(3,3)

print(matrix1)
print("\n")
print(matrix2)

print("\n")
dotMatrix = matrix1.dot(matrix2)
print(dotMatrix)

print("\n")
TMatrix = dotMatrix.transpose()
print(TMatrix)


[[-0.63509414 -0.60649745 -1.32946409]
 [ 0.55098647 -1.1217482  -1.27327913]
 [-0.50401177  2.16431877  0.21225895]]


[[ 1.1823587  -0.04896672 -0.04482684]
 [-0.1093743  -0.89928838  0.25000047]
 [ 0.59730557  0.42908436  1.30422332]]


[[-1.47867016  0.00606234 -1.85707344]
 [ 0.01361736  0.43545096 -1.96577689]
 [-0.70586009 -1.83058993  0.84050703]]


[[-1.47867016  0.01361736 -0.70586009]
 [ 0.00606234  0.43545096 -1.83058993]
 [-1.85707344 -1.96577689  0.84050703]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [10]:
#please provide your answer below this line.

import numpy as np
M = np.matrix('[55,25,15; 30,44,2; 11,45,77]')
print(M)

print("\n")
det = np.linalg.det(M)
print(int(det))


[[55 25 15]
 [30 44  2]
 [11 45 77]]


137180
