<a href="https://colab.research.google.com/github/Natasha1305/LEARN.PY/blob/main/TASK-13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [ ]:
#please enter your code below this line.
import numpy as np
A = np.arange(9).reshape(3,3)
print("A : \n", A)
print("\n")

sum = np.sum(A);
print("The sum of the array is", sum)



2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [ ]:
#please enter your code below this line.
import numpy as np
A = np.arange(9).reshape(3,3)
print("A : \n", A)
print("\n")

rowSum = np.sum(A,1)
print("The row sum of A is", rowSum)

colSum = np.sum(A,0)
print("The column sum of A is", colSum)


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [ ]:
#please enter your code belowthis line.
import numpy as np
A = np.arange(16).reshape(4,4)
print("A : \n", A)
print("\n")

print("The minimum value in the array is",np.min(A))
print("The maximum value in the array is",np.max(A))
print("The mean of the values in the array is",np.mean(A))



4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [19]:
#please enter your code below this line.
import numpy as np
A = np.arange(100).reshape(10,10)
print("A : \n", A)
print("\n")

print("The 7th row is", A[7])
print("\n")
print("The 4-8th rows are : \n", A[4:8])
print("\n")
print("The value at index A[5][5] is :", A[5][5])
print("\n")
print("The 5th column is :", A[:,5])
print("\n")
print("The 2-5th columns are :\n", A[:,2:5])





A : 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


The 7th row is [70 71 72 73 74 75 76 77 78 79]


The 4-8th rows are : 
 [[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]


The value at index A[5][5] is : 55


The 5th column is : [ 5 15 25 35 45 55 65 75 85 95]


The 2-5th columns are :
 [[ 2  3  4]
 [12 13 14]
 [22 23 24]
 [32 33 34]
 [42 43 44]
 [52 53 54]
 [62 63 64]
 [72 73 74]
 [82 83 84]
 [92 93 94]]
